server {
    listen 80;
    listen [::]:80;
    server_name xn--dmonstrateur-beb.tech www.xn--dmonstrateur-beb.tech;
    return 301 https://xn--dmonstrateur-beb.tech$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name www.xn--dmonstrateur-beb.tech;

    ssl_certificate /etc/letsencrypt/live/xn--dmonstrateur-beb.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xn--dmonstrateur-beb.tech/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://xn--dmonstrateur-beb.tech$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name xn--dmonstrateur-beb.tech;

    ssl_certificate /etc/letsencrypt/live/xn--dmonstrateur-beb.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xn--dmonstrateur-beb.tech/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/demonstrateur;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
