# Generated by Django 5.0.1 on 2026-06-19 16:36

import apps.quiz.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text="Numéro de la question (ordre d'affichage, ex: 1 à 10)", unique=True)),
                ('question_text', models.TextField(help_text='Énoncé de la question')),
                ('image', models.FileField(blank=True, help_text='Image affichée au centre de la question', upload_to=apps.quiz.models.get_quiz_image_path)),
                ('question_type', models.CharField(choices=[('mcq', 'QCM (4 choix)'), ('truefalse', 'Vrai / Faux')], default='mcq', max_length=10)),
                ('choices', models.JSONField(default=list, help_text='Liste des propositions (ordre A, B, C, D)')),
                ('correct_index', models.PositiveSmallIntegerField(help_text='Index (0-based) de la bonne réponse dans `choices`')),
                ('anecdote', models.TextField(blank=True, help_text='Anecdote affichée après la révélation de la réponse')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question Quiz',
                'verbose_name_plural': 'Questions Quiz',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default=apps.quiz.models.generate_quiz_room_code, help_text='Code unique de la room (6 caractères)', max_length=6, unique=True)),
                ('host_token', models.UUIDField(default=uuid.uuid4, help_text="Token secret de l'hôte, requis pour piloter la room", unique=True)),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('playing', 'En cours'), ('showing_answer', 'Révélation'), ('finished', 'Terminé')], default='waiting', max_length=20)),
                ('current_question_index', models.IntegerField(default=0, help_text='Index de la question en cours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room Quiz',
                'verbose_name_plural': 'Rooms Quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(help_text='Pseudo du joueur', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('session_token', models.UUIDField(default=uuid.uuid4, help_text='Token unique pour la reconnexion', unique=True)),
                ('channel_name', models.CharField(blank=True, help_text='Nom du channel WebSocket actuel', max_length=255)),
                ('is_connected', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='quiz.quizroom')),
            ],
            options={
                'verbose_name': 'Joueur Quiz',
                'verbose_name_plural': 'Joueurs Quiz',
                'ordering': ['-score', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_index', models.IntegerField(help_text='Index (0-based) de la proposition choisie')),
                ('is_correct', models.BooleanField()),
                ('points_earned', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(help_text='Temps de réponse en millisecondes')),
                ('answer_order', models.IntegerField(default=0, help_text='Ordre de réponse (1er, 2ème, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizplayer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='quiz.quizquestion')),
            ],
            options={
                'verbose_name': 'Réponse Quiz',
                'verbose_name_plural': 'Réponses Quiz',
                'ordering': ['answer_order'],
                'unique_together': {('player', 'question')},
            },
        ),
    ]
