# Generated by Django 5.0.1 on 2026-09-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizplayer',
            name='room',
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='QuizPlayer',
        ),
        migrations.DeleteModel(
            name='QuizRoom',
        ),
    ]
